### ISSUE TITLE
IoT Video Live Stream is already available for debugging

### ISSUE THREAD

**Issue by mybdye** [cjj25/RTS3903N-Tuya-RTSPServer#3]
[https://iot.tuya.com](https://iot.tuya.com/
)

<img width="522" alt="截屏2022-09-28 17 21 26" src="https://user-images.githubusercontent.com/21116709/192742057-c5a51cfe-c4c9-41d2-93f7-7c9d1bebba10.png">
<img width="1497" alt="截屏2022-09-28 17 22 03" src="https://user-images.githubusercontent.com/21116709/192742098-2aa8448b-74cc-4887-ac50-10061887f39d.png">

`type = hls`  works with VLC/IINA player on my laptop

<img width="574" alt="截屏2022-09-28 17 27 03" src="https://user-images.githubusercontent.com/21116709/192743171-7ea2bb70-97ef-4f45-8b5b-2fe6772b8c04.png">

**Comment by mybdye** [comment]
My device is Tuya SC-WA002.

**Comment by jcconnell** [comment]
Interesting. This worked for me as well. I have a preference for a local RTSP stream though.
